version: '3.8'

services:
  telegram-channel-curator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_channel_curator
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./:/app/sessions
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
